-- 8. Create Coupons Table
CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  discount_type TEXT NOT NULL, -- 'percentage' or 'flat'
  discount_value DECIMAL(10, 2) NOT NULL,
  min_purchase DECIMAL(10, 2) DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  expiry_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initial Coupons
INSERT INTO coupons (code, discount_type, discount_value, min_purchase) VALUES
('WELCOME10', 'percentage', 10, 500), -- 10% off on min 500
('SUVAI50', 'flat', 50, 200);      -- Flat 50 off on min 200

-- Enable RLS for coupons (Public can check code availability)
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Coupons" ON coupons FOR SELECT USING (true);
