-- 7. Create Payments Table
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  payment_id TEXT UNIQUE, -- Razorpay Payment ID
  razorpay_order_id TEXT, -- Razorpay Order ID
  amount DECIMAL(10, 2),
  currency TEXT DEFAULT 'INR',
  status TEXT DEFAULT 'pending', -- pending, completed, failed, refunded
  method TEXT, -- card, upi, netbanking, etc.
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for payments
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Policy for admins to view all payments
CREATE POLICY "Admin All Payments" ON payments FOR ALL USING (
  EXISTS (SELECT 1 FROM clients WHERE id = auth.uid() AND role = 'admin')
);

-- Policy for users to view their own payments
CREATE POLICY "Users Own Payments" ON payments FOR SELECT USING (
  EXISTS (SELECT 1 FROM orders WHERE id = payments.order_id AND client_id = auth.uid())
);
