-- SUVAI PAYMENTS & COUPONS MIGRATION V4
-- Run this in Supabase SQL Editor

-- 1. Create Coupons Table
CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  discount_type TEXT CHECK (discount_type IN ('percentage', 'fixed')) NOT NULL,
  value DECIMAL(10, 2) NOT NULL,
  expiry_date TIMESTAMPTZ,
  usage_limit INTEGER DEFAULT 100,
  used_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive'))
);

-- 2. Create Payments Table
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  transaction_id TEXT UNIQUE,
  amount DECIMAL(10, 2) NOT NULL,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Success', 'Failed')),
  provider TEXT DEFAULT 'Razorpay',
  raw_response JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Seed some initial Coupons
INSERT INTO coupons (code, discount_type, value, expiry_date) VALUES 
('SUVAI10', 'percentage', 10.00, NOW() + INTERVAL '30 days'),
('WELCOME50', 'fixed', 50.00, NOW() + INTERVAL '1 year')
ON CONFLICT (code) DO NOTHING;
