-- Migration v11: support_tickets and site_settings tables

-- Support Tickets
CREATE TABLE IF NOT EXISTS support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  order_id TEXT,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_support_tickets_client_id ON support_tickets(client_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets(status);

-- Site Settings (key-value store)
CREATE TABLE IF NOT EXISTS site_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed default settings
INSERT INTO site_settings (key, value) VALUES
  ('store_name', 'Suvai Premium Spices'),
  ('support_email', 'support@rajasuvai.com'),
  ('business_phone', '+91 98765 43210'),
  ('warehouse_address', '12, Kuruvikkaran Salai, Anna Nagar, Madurai, Tamil Nadu 625020'),
  ('low_stock_threshold', '10'),
  ('shipping_fee', '50'),
  ('announcement_enabled', 'true'),
  ('announcement_text', 'Free shipping on orders above ₹500 | Use code SPICE10 for 10% off')
ON CONFLICT (key) DO NOTHING;
