-- SUVAI ORDER MANAGEMENT MIGRATION V3
-- Run this in Supabase SQL Editor

-- 1. Create Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Update Order Statuses to match the new flow
-- Flow: Pending → Packed → Shipped → Delivered → Cancelled
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE orders ADD CONSTRAINT orders_status_check CHECK (status IN ('Pending', 'Packed', 'Shipped', 'Delivered', 'Cancelled'));

-- Migrating existing data if any (mapping 'ordered' to 'Pending')
UPDATE orders SET status = 'Pending' WHERE status = 'ordered';
UPDATE orders SET status = 'Shipped' WHERE status = 'shipped';
UPDATE orders SET status = 'Delivered' WHERE status = 'delivered';

-- 3. Ensure all orders have a Pending status by default
ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'Pending';
