-- Run this in the Supabase SQL Editor

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price TEXT NOT NULL,
  category TEXT,
  image TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Inventory Table
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER DEFAULT 0,
  low_stock_threshold INTEGER DEFAULT 10,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Clients Table
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  phone TEXT,
  address TEXT, -- Legacy structured address or fallback
  photo_url TEXT,
  role TEXT DEFAULT 'customer',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3a. Create Addresses Table (Detailed)
CREATE TABLE IF NOT EXISTS addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  full_name TEXT,
  phone TEXT,
  pincode TEXT,
  address_line1 TEXT,
  address_line2 TEXT,
  city TEXT,
  state TEXT,
  tag TEXT DEFAULT 'Home', -- Home, Work, Other
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'ordered', 
  total_price DECIMAL(10, 2),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create Sales Table
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  total_amount DECIMAL(10, 2),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Insert Initial Products (Premium Spices)
INSERT INTO products (name, price, category, image, description) VALUES
('Organic Turmeric Powder', '₹250', 'Spices', 'https://images.unsplash.com/photo-1615485290382-441e4d019cb5?w=800&auto=format&fit=crop', 'Pure hand-ground turmeric with high curcumin content.'),
('Kashmiri Red Chili', '₹320', 'Spices', 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop', 'Vibrant red color with a mild, aromatic heat.'),
('Whole Green Cardamom', '₹950', 'Spices', 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop', 'Premium grade cardamom pods from the hills of Idukki.'),
('Malabar Black Pepper', '₹450', 'Spices', 'https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=800&auto=format&fit=crop', 'Bold and spicy whole black peppercorns.');

-- Enable Public Access (Temporary for testing)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Select" ON products FOR SELECT USING (true);
CREATE POLICY "Public Insert" ON products FOR INSERT WITH CHECK (true);

-- Enable access to clients table
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Select Clients" ON clients FOR SELECT USING (true);
CREATE POLICY "Public Insert Clients" ON clients FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Clients" ON clients FOR UPDATE USING (true);
