-- SUVAI ADMIN PANEL MIGRATION V2
-- Run this in Supabase SQL Editor

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  parent_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add Category ID, SKU, and Status to Products
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sku TEXT UNIQUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive'));

-- 3. Populate Initial Categories
INSERT INTO categories (name) VALUES 
('Spices'), 
('Grains'), 
('Sweets'), 
('Pickles')
ON CONFLICT (name) DO NOTHING;

-- 4. Map existing products to categories (best effort)
UPDATE products SET category_id = (SELECT id FROM categories WHERE name = 'Spices') WHERE category = 'Spices';
UPDATE products SET category_id = (SELECT id FROM categories WHERE name = 'Grains') WHERE category = 'Grains';
UPDATE products SET category_id = (SELECT id FROM categories WHERE name = 'Sweets') WHERE category = 'Sweets';
UPDATE products SET category_id = (SELECT id FROM categories WHERE name = 'Pickles') WHERE category = 'Pickles';

-- 5. Seed Inventory for existing products if missing
INSERT INTO inventory (product_id, quantity, low_stock_threshold)
SELECT id, 50, 10 FROM products
WHERE id NOT IN (SELECT product_id FROM inventory)
ON CONFLICT DO NOTHING;
