-- Migration 140: reconcile the live schema with what the application code
-- actually reads and writes. Verified empirically against the live Supabase
-- project on 2026-08-04 — every item below was confirmed missing, and each one
-- breaks a user-facing flow today.
--
-- Root cause: migrations 040+ were authored but never applied to this project.
-- Rather than replay them piecemeal, this brings the schema to the state the
-- current code requires. Safe to re-run (all guards are IF NOT EXISTS).

-- ---------------------------------------------------------------------------
-- 1. cart_items — MISSING ENTIRELY.
-- controllers/cartController.js (GET/POST/PUT/DELETE /api/cart, /api/cart/sync)
-- and paymentController.fulfillOrder() all use this table, so the logged-in
-- cart is completely non-functional without it.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (client_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_cart_items_client_id ON cart_items(client_id);

-- ---------------------------------------------------------------------------
-- 2. sales — MISSING. Used by GET /api/admin/dashboard-stats to compute total
-- revenue, so the admin dashboard revenue figure is broken without it.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  total_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sales_created_at ON sales(created_at);

-- ---------------------------------------------------------------------------
-- 3. orders — missing columns written by paymentController.createOrder().
-- Without these the order INSERT fails outright, so checkout cannot complete.
-- ---------------------------------------------------------------------------
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_id BIGINT REFERENCES addresses(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS metadata JSONB;

-- ---------------------------------------------------------------------------
-- 4. orders.status — the existing CHECK constraint only allows the fulfilment
-- statuses, but the payment flow writes 'pending_payment' (on order creation)
-- and 'paid' (on successful payment), both of which violate it. Order
-- cancellation logic in server.js also expects these values.
-- ---------------------------------------------------------------------------
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE orders ADD CONSTRAINT orders_status_check
  CHECK (status IN ('pending_payment', 'paid', 'Pending', 'Packed', 'Shipped', 'Delivered', 'Cancelled'));

-- ---------------------------------------------------------------------------
-- 5. payments — missing columns written by fulfillOrder() and the webhook.
-- These exist in migration 040, which was never applied here.
-- ---------------------------------------------------------------------------
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_id TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS razorpay_order_id TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS method TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS metadata JSONB;

CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_payment_id ON payments(payment_id) WHERE payment_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 6. RLS. All backend DB access runs as the Supabase anon key (the caller's
-- JWT is not forwarded per-request), so these tables need policies that permit
-- the anon role. Request-level authorisation is enforced in the Express layer
-- by authMiddleware.js, which verifies the JWT and scopes every query by
-- client_id. NOTE: this means the anon key alone can read/write these tables —
-- moving the backend to a SUPABASE_SERVICE_ROLE_KEY and tightening these
-- policies is the correct hardening step, tracked separately.
-- ---------------------------------------------------------------------------
ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Backend manages cart_items" ON cart_items;
CREATE POLICY "Backend manages cart_items" ON cart_items
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Backend manages sales" ON sales;
CREATE POLICY "Backend manages sales" ON sales
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
