-- ==============================================================
-- SUVAI — APPLY THIS IN THE SUPABASE SQL EDITOR
-- ==============================================================
-- Combines migrations 120, 130 and 140. Every statement below was
-- verified against the live database on 2026-08-04 as genuinely
-- missing. Until this runs, the following are broken in production:
--   * Checkout / order placement (fails outright)
--   * Logged-in cart (cart_items table does not exist)
--   * Admin dashboard revenue (sales table does not exist)
--   * Contact Us form (RLS blocks insert)
--   * Newsletter signup (table does not exist)
-- Safe to re-run: every statement is guarded.
-- ==============================================================

-- ################ 120_support_tickets_public_insert.sql ################
-- Migration 120: allow the public Contact Us form (SupportPage.tsx -> POST /api/support)
-- to insert support tickets for guests, not just logged-in users.
--
-- Row Level Security on support_tickets currently has no INSERT policy, so every
-- insert through the (anon-key) backend client is rejected — including from
-- logged-in users, since the backend does not forward the caller's JWT to
-- Supabase per-request; all backend DB access runs as the anon key.

ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert on support_tickets" ON support_tickets;
CREATE POLICY "Allow public insert on support_tickets"
  ON support_tickets
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- ################ 130_newsletter_subscribers.sql ################
-- Migration 130: create the newsletter_subscribers table.
-- POST /api/newsletter (used by the Footer subscribe form) references this
-- table but no prior migration created it — the endpoint has been failing
-- with "Could not find the table 'public.newsletter_subscribers'".

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  subscribed_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert on newsletter_subscribers" ON newsletter_subscribers;
CREATE POLICY "Allow public insert on newsletter_subscribers"
  ON newsletter_subscribers
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- ################ 140_checkout_schema_reconciliation.sql ################
-- Migration 140: reconcile the live schema with what the application code
-- actually reads and writes. Verified empirically against the live Supabase
-- project on 2026-08-04 — every item below was confirmed missing, and each one
-- breaks a user-facing flow today.
--
-- Root cause: migrations 040+ were authored but never applied to this project.
-- Rather than replay them piecemeal, this brings the schema to the state the
-- current code requires. Safe to re-run (all guards are IF NOT EXISTS).

-- ---------------------------------------------------------------------------
-- 1. cart_items — MISSING ENTIRELY.
-- controllers/cartController.js (GET/POST/PUT/DELETE /api/cart, /api/cart/sync)
-- and paymentController.fulfillOrder() all use this table, so the logged-in
-- cart is completely non-functional without it.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (client_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_cart_items_client_id ON cart_items(client_id);

-- ---------------------------------------------------------------------------
-- 2. sales — MISSING. Used by GET /api/admin/dashboard-stats to compute total
-- revenue, so the admin dashboard revenue figure is broken without it.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  total_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sales_created_at ON sales(created_at);

-- ---------------------------------------------------------------------------
-- 3. orders — missing columns written by paymentController.createOrder().
-- Without these the order INSERT fails outright, so checkout cannot complete.
-- ---------------------------------------------------------------------------
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_id BIGINT REFERENCES addresses(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS metadata JSONB;

-- ---------------------------------------------------------------------------
-- 4. orders.status — the existing CHECK constraint only allows the fulfilment
-- statuses, but the payment flow writes 'pending_payment' (on order creation)
-- and 'paid' (on successful payment), both of which violate it. Order
-- cancellation logic in server.js also expects these values.
-- ---------------------------------------------------------------------------
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE orders ADD CONSTRAINT orders_status_check
  CHECK (status IN ('pending_payment', 'paid', 'Pending', 'Packed', 'Shipped', 'Delivered', 'Cancelled'));

-- ---------------------------------------------------------------------------
-- 5. payments — missing columns written by fulfillOrder() and the webhook.
-- These exist in migration 040, which was never applied here.
-- ---------------------------------------------------------------------------
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_id TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS razorpay_order_id TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS method TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS metadata JSONB;

CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_payment_id ON payments(payment_id) WHERE payment_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 6. RLS. All backend DB access runs as the Supabase anon key (the caller's
-- JWT is not forwarded per-request), so these tables need policies that permit
-- the anon role. Request-level authorisation is enforced in the Express layer
-- by authMiddleware.js, which verifies the JWT and scopes every query by
-- client_id. NOTE: this means the anon key alone can read/write these tables —
-- moving the backend to a SUPABASE_SERVICE_ROLE_KEY and tightening these
-- policies is the correct hardening step, tracked separately.
-- ---------------------------------------------------------------------------
ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Backend manages cart_items" ON cart_items;
CREATE POLICY "Backend manages cart_items" ON cart_items
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Backend manages sales" ON sales;
CREATE POLICY "Backend manages sales" ON sales
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

